version: 2
jobs:
  test:
    docker:
      - image: theasp/clojurescript-nodejs:latest
      - image: postgres:9.5-alpine
        environment:
          POSTGRES_USER: admin
          POSTGRES_DB: postgres
    steps:
      - checkout
      - run: lein test

workflows:
  version: 2
  test:
    jobs:
      - test
